// Copyright (c) 2022-2023, Karagatan LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: raftbadger.proto

package raftbadger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftLogType int32

const (
	RaftLogType_LogCommand              RaftLogType = 0
	RaftLogType_LogNoop                 RaftLogType = 1
	RaftLogType_LogAddPeerDeprecated    RaftLogType = 2
	RaftLogType_LogRemovePeerDeprecated RaftLogType = 3
	RaftLogType_LogBarrier              RaftLogType = 4
	RaftLogType_LogConfiguration        RaftLogType = 5
)

// Enum value maps for RaftLogType.
var (
	RaftLogType_name = map[int32]string{
		0: "LogCommand",
		1: "LogNoop",
		2: "LogAddPeerDeprecated",
		3: "LogRemovePeerDeprecated",
		4: "LogBarrier",
		5: "LogConfiguration",
	}
	RaftLogType_value = map[string]int32{
		"LogCommand":              0,
		"LogNoop":                 1,
		"LogAddPeerDeprecated":    2,
		"LogRemovePeerDeprecated": 3,
		"LogBarrier":              4,
		"LogConfiguration":        5,
	}
)

func (x RaftLogType) Enum() *RaftLogType {
	p := new(RaftLogType)
	*p = x
	return p
}

func (x RaftLogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftLogType) Descriptor() protoreflect.EnumDescriptor {
	return file_raftbadger_proto_enumTypes[0].Descriptor()
}

func (RaftLogType) Type() protoreflect.EnumType {
	return &file_raftbadger_proto_enumTypes[0]
}

func (x RaftLogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftLogType.Descriptor instead.
func (RaftLogType) EnumDescriptor() ([]byte, []int) {
	return file_raftbadger_proto_rawDescGZIP(), []int{0}
}

type RaftLog struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Index      uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term       uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Type       RaftLogType            `protobuf:"varint,3,opt,name=type,proto3,enum=raftbadger.RaftLogType" json:"type,omitempty"`
	Data       []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Extensions []byte                 `protobuf:"bytes,5,opt,name=extensions,proto3" json:"extensions,omitempty"`
	// appended_at is the time the leader first appended this entry, stored as
	// Unix nanoseconds. 0 means unset (raft.Log.AppendedAt was the zero time).
	AppendedAt    int64 `protobuf:"varint,6,opt,name=appended_at,json=appendedAt,proto3" json:"appended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftLog) Reset() {
	*x = RaftLog{}
	mi := &file_raftbadger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftLog) ProtoMessage() {}

func (x *RaftLog) ProtoReflect() protoreflect.Message {
	mi := &file_raftbadger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftLog.ProtoReflect.Descriptor instead.
func (*RaftLog) Descriptor() ([]byte, []int) {
	return file_raftbadger_proto_rawDescGZIP(), []int{0}
}

func (x *RaftLog) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftLog) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftLog) GetType() RaftLogType {
	if x != nil {
		return x.Type
	}
	return RaftLogType_LogCommand
}

func (x *RaftLog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RaftLog) GetExtensions() []byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *RaftLog) GetAppendedAt() int64 {
	if x != nil {
		return x.AppendedAt
	}
	return 0
}

var File_raftbadger_proto protoreflect.FileDescriptor

const file_raftbadger_proto_rawDesc = "" +
	"\n" +
	"\x10raftbadger.proto\x12\n" +
	"raftbadger\"\xb5\x01\n" +
	"\aRaftLog\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.raftbadger.RaftLogTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"extensions\x18\x05 \x01(\fR\n" +
	"extensions\x12\x1f\n" +
	"\vappended_at\x18\x06 \x01(\x03R\n" +
	"appendedAt*\x87\x01\n" +
	"\vRaftLogType\x12\x0e\n" +
	"\n" +
	"LogCommand\x10\x00\x12\v\n" +
	"\aLogNoop\x10\x01\x12\x18\n" +
	"\x14LogAddPeerDeprecated\x10\x02\x12\x1b\n" +
	"\x17LogRemovePeerDeprecated\x10\x03\x12\x0e\n" +
	"\n" +
	"LogBarrier\x10\x04\x12\x14\n" +
	"\x10LogConfiguration\x10\x05B'Z%go.arpabet.com/raft-badger;raftbadgerb\x06proto3"

var (
	file_raftbadger_proto_rawDescOnce sync.Once
	file_raftbadger_proto_rawDescData []byte
)

func file_raftbadger_proto_rawDescGZIP() []byte {
	file_raftbadger_proto_rawDescOnce.Do(func() {
		file_raftbadger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftbadger_proto_rawDesc), len(file_raftbadger_proto_rawDesc)))
	})
	return file_raftbadger_proto_rawDescData
}

var file_raftbadger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raftbadger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_raftbadger_proto_goTypes = []any{
	(RaftLogType)(0), // 0: raftbadger.RaftLogType
	(*RaftLog)(nil),  // 1: raftbadger.RaftLog
}
var file_raftbadger_proto_depIdxs = []int32{
	0, // 0: raftbadger.RaftLog.type:type_name -> raftbadger.RaftLogType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raftbadger_proto_init() }
func file_raftbadger_proto_init() {
	if File_raftbadger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftbadger_proto_rawDesc), len(file_raftbadger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raftbadger_proto_goTypes,
		DependencyIndexes: file_raftbadger_proto_depIdxs,
		EnumInfos:         file_raftbadger_proto_enumTypes,
		MessageInfos:      file_raftbadger_proto_msgTypes,
	}.Build()
	File_raftbadger_proto = out.File
	file_raftbadger_proto_goTypes = nil
	file_raftbadger_proto_depIdxs = nil
}
